### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by raynigon**
Since a few Weeks the google play store scrapper is no longer working for us.
With the dependency update it works as expected.

Following Dependencies will be updated with this PR:
* @snyk/protect
* google-play-scraper
* prom-client

Should fix:
* https://github.com/timoa/app-stores-prometheus-exporter/pull/116
* https://github.com/timoa/app-stores-prometheus-exporter/pull/110
* https://github.com/timoa/app-stores-prometheus-exporter/pull/109

### CODE REVIEW

**Comment by raynigon** [comment]
Hi @timoa ,

would it be possible to merge this in the near future?

**Comment by timoa** [comment]
Hi @raynigon!

Sorry, I planned to check some of the dependency updates manually and I was too busy before going on holiday :/

I'm going to test it today (mainly the major update on Google Play Scraper) and merge ASAP.

It will be done today if no issue with this update.

Thanks for using this project and have created this PR!

Cheers,
Damien

**Comment by raynigon** [comment]
Hi Damien,

And a big Thank you for providing this wounderful piece of software!
Our iOS Devlopers love it, because we generated Grafana Alerts with it.

is there anything I can do to suport you?
I tested all changes in this PR locally and it worked for me.

**Comment by timoa** [comment]
Hi @raynigon!

Thanks for the PR and the tests you did! 

I could not merge your PR since Renovate is updating the Snyk protect dependency (I need to exclude it since there is a daily build) and I was busy comparing the sha256 of each dependency.

Happy that your iOS developers love the project! I'm planning to update the Grafana dashboards too!

Thanks again!
Damien

**Pull request closed without merging**
